### ISSUE TITLE
Windows background black and can't be changed anymore

### ISSUE THREAD

**Issue by reaseno** [simeononsecurity/Windows-Optimize-Harden-Debloat#10]
Executed with manual install on a Win10 Enterprise v1909. Now I can't change background color or picture. Windows says the settings are disabled as of a organisation restriction.

Tested on a Windows in a virtualbox and not in a domain.

Is there a revert function for the scripts?

**Comment by simeononsecurity** [comment]
@reaseno 

There is not a built in function to revert these scripts at this time. I'm glad you were tested before implementing, not everyone does that.
As far as the background color and picture, there is nothing in this script that would modify those settings. Or at least there shouldn't be. Seems you've caught a bad merge that happened when we made multiple copies of the script. I've now fixed that. https://github.com/simeononsecurity/Windows-Optimize-Harden-Debloat/commit/83b980e74cf1bbbadf84ac34ccf9d9107d74c44c
