### ISSUE TITLE
Disable Recall

### ISSUE THREAD

**Issue by mi-lrn** [simeononsecurity/Windows-Optimize-Harden-Debloat#106]
Hello!

Great script! Just wanted to let you know in the latest windows builds, there is a new invasive AI feature called Recall that should be disabled.

Through command prompt it's as easy as DISM /Online /Disable-Feature /FeatureName:"Recall," but I'm not sure exactly where the registry value is so it can be disabled through ps.

Thanks for taking the time to read my request.

![image](https://github.com/user-attachments/assets/b576610a-2c23-4628-b3da-1a3ba62f725a)

**Comment by simeononsecurity** [comment]
resolved
