### ISSUE TITLE
Firefox Extensions

### ISSUE THREAD

**Issue by Konrad90** [simeononsecurity/Windows-Optimize-Harden-Debloat#11]
I think you should add to the readme information that several Firefox addons will be installed and a list of them and what they do.

Best regards,
Konrad

**Comment by simeononsecurity** [comment]
Thank you for the suggestion. We didn't want to flood the readme with a bunch of additional information..
We are working on increasing the documentation as much as possible while still keeping it readable and concise. 

In the mean time, take a look at the following to get more information on the specific Firefox configurations and extensions this script utilizes.
- https://github.com/simeononsecurity/FireFox-Privacy-Script
- https://github.com/simeononsecurity/FireFox-STIG-Script
- https://ffprofile.com/
- https://www.privacytools.io/browsers/#about_config

**Comment by simeononsecurity** [comment]
https://github.com/simeononsecurity/Windows-Optimize-Harden-Debloat/tree/826e8f5705aee89407cb5b9db9bc37cadd208662

**Comment by AadilGillani** [comment]
now i am not able to download any thing from chrome browser any way to disable these extensions or any othe rway to fix the issue of not being able to download anything from chrome browser

**Comment by couleurm** [comment]
On a similar note, is there any unattended ways to install Firefox extensions that will get updates?

**Comment by simeononsecurity** [comment]
> On a similar note, is there any unattended ways to install Firefox extensions that will get updates?

Previously, the script disabled extension updates per the [Cyber.mil FireFox STIG](https://public.cyber.mil/stigs/downloads/)
This is one of those things that don't make any sense and should've been corrected by us already. Our enterprise targeted [Standalone-Windows-STIG-Script](https://github.com/simeononsecurity/Standalone-Windows-STIG-Script) will have the STIG enforced still.

We've updated the script to reverse those settings. Extensions are allowed to auto update now.
https://github.com/simeononsecurity/Windows-Optimize-Harden-Debloat/commit/1cb73b096c2a6401634383c52477aceb4eede25d
