### ISSUE TITLE
Can i revert this ?

### ISSUE THREAD

**Issue by loursmartial** [simeononsecurity/Windows-Optimize-Harden-Debloat#12]
**Describe the bug**
-Lost my Firefox history log and session with 30+ tabs 
-Can't access my nerwork drives anymore

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 89

Edit: forgot to mention, there are no system point I can restore to for some reason..

**Comment by simeononsecurity** [comment]
The script does not have built in restore points. If you were unsure, you should've tested in a vm or taken your own restore point.  

I can tell you though, with 100% certainty, that the changes made by the script wouldn't have made you lose your Firefox history or tabs unless you also ran my Firefox privacy or security researcher script. This script only includes the STIG Firefox settings, which actually are configured to do the exact opposite of what you're having issues with. 

The script disables SMB v1 and enables some SMBv2 hardening like requiring encryption and signing.
Additionally, it will disable anonymous access to any network share. All this is documented and mentioned [here](https://dl.cyber.mil/stigs/zip/U_MS_Windows_Defender_Antivirus_V2R1_STIG.zip), which is mentioned in the readme.

I can't troubleshoot your NAS for you, but I suggest you review its settings and configure it to more secure standards.

The quickest answer here is to tell you to reinstall windows. If you're not used to running hardened versions of windows, especially so with DoD STIGs, you should know that it does disable quite a lot. Please take the time to review the documentation I have linked in the readme. 

I also have another version of the script that doesn't do the hardening like in this script.
Please see [here](https://github.com/simeononsecurity/Windows-Optimize-Debloat) for the Optimize an Debloat script.

**Comment by simeononsecurity** [comment]
<img width="862" alt="image" src="https://user-images.githubusercontent.com/4913771/119525710-4369ee00-bd6e-11eb-9876-fabc157a1ea7.png">
