### ISSUE TITLE
the problem with use port 443 https?

### ISSUE THREAD

**Issue by impet14** [simeononsecurity/Windows-Optimize-Harden-Debloat#18]
I cannot install some software using port 443 and HTTPS. for example, I cannot install automated installing script.

Could you tell me how to fix it?

**Comment by simeononsecurity** [comment]
You'll need to open the port on the Windows Firewall.
If that fails, chances are it's because the application is using an insecure version of it hashing or TLS functions. If that is the case, you're likely going to want to restore from a snapshot or reinstall windows.
What application is it?
