### ISSUE TITLE
Windows 11 - Remote desktop

### ISSUE THREAD

**Issue by Sakonji** [simeononsecurity/Windows-Optimize-Harden-Debloat#20]
Hi,

I ran the script on a remote desktop, and I lost the connection in the middle of the script, I lost the connection. 
When I tried to enable Remote accès, the switch button was still off.

I've modified Group Policy, and have a look in Registery, but everything is ok...

Any idea?

Many thanks for considering my request.
Sakonji

**Comment by nsk** [comment]
Votre administrateur peut modifier sa configuration à distance. Il se peut que l'activité sur cet appareil soit gérée en dehors de Chrome. En savoir plus
Extensions
L'administrateur de cet appareil a installé des extensions 

this script is dangerous ................... report on github

**Comment by simeononsecurity** [comment]
> Votre administrateur peut modifier sa configuration à distance. Il se peut que l'activité sur cet appareil soit gérée en dehors de Chrome. En savoir plus
> Extensions
> L'administrateur de cet appareil a installé des extensions
> 
> this script is dangerous ................... report on github

The extensions are documented as per https://github.com/simeononsecurity/Windows-Optimize-Harden-Debloat#additions
As with any script, you should test it in a lab environment before running on any production system. There is no danger here other than your misunderstanding and your inability to read the readme.
In addition to this, your comment here is not relevant to this issue. If you have any issues with this script, please open your own issue.

Les extensions sont documentées conformément à https://github.com/simeononsecurity/Windows-Optimize-Harden-Debloat#additions Comme pour tout script, vous devez le tester dans un environnement lab avant de l'exécuter sur un système de production. Il n'y a pas de danger ici autre que votre incompréhension et votre incapacité à lire le readme. En plus de cela, votre commentaire ici n'est pas pertinent pour cette question. Si vous rencontrez des problèmes avec ce script, veuillez ouvrir votre propre problème.

**Comment by simeononsecurity** [comment]
> Hi,
> 
> I ran the script on a remote desktop, and I lost the connection in the middle of the script, I lost the connection.
> When I tried to enable Remote accès, the switch button was still off.
> 
> I've modified Group Policy, and have a look in Registery, but everything is ok...
> 
> Any idea?
> 
> Many thanks for considering my request.
> Sakonji

I'll need more details to rectify your issue here.
The script as part of the [Windows 10 V2R2](https://public.cyber.mil/stigs/downloads/) as documented in the readme, does enable additional remote desktop security settings. None of which have we noted as causing any issues. It should not disable remote desktop if you have it enabled already. 
Please send me a screenshot of the settings you enabled for remote desktop and provide as many details as possible.

**Comment by simeononsecurity** [comment]
Closing.

Reasons:
- Unable to recreate issue
- User did not respond with more details

**Comment by simeononsecurity** [comment]
https://github.com/simeononsecurity/Windows-Optimize-Harden-Debloat/discussions/81
