### ISSUE TITLE
Can't revert changes

### ISSUE THREAD

**Issue by mh4mzak** [simeononsecurity/Windows-Optimize-Harden-Debloat#21]
Hi I ran the automated install script thinking it would only download it not run it and now I have 5+ extensions installed on edge and i'm sure a lot of other stuff I can't see. I can't remove the extensions because they're 'Installed by my organisation' even though I don't have one. 
How can I get rid of all of it?

**Comment by simeononsecurity** [comment]
This is partially documented here 
https://github.com/simeononsecurity/Windows-Optimize-Harden-Debloat#additions

To revert the changes, you'll need to import the ADMX templates from here https://github.com/simeononsecurity/STIG-Compliant-Domain-Prep/tree/master/Files/PolicyDefinitions using this guide https://www.poremsky.com/windows/use-group-policy-admx-files-in-windows-7-or-8/ which still applies to W10 and W11

In the windows run box, open "gpedit.msc" as an administrator
![image](https://user-images.githubusercontent.com/4913771/145898591-9e8a4da8-f00f-4ea4-b8fe-4f0b2b1476bd.png)


Navigate to here and clear out these values 
![image](https://user-images.githubusercontent.com/4913771/145898735-1babe894-0590-4efe-b15f-8b12c8ea86f1.png)

**Comment by peter9811** [comment]
> This is partially documented here https://github.com/simeononsecurity/Windows-Optimize-Harden-Debloat#additions
> 
> To revert the changes, you'll need to import the ADMX templates from here https://github.com/simeononsecurity/STIG-Compliant-Domain-Prep/tree/master/Files/PolicyDefinitions using this guide https://www.poremsky.com/windows/use-group-policy-admx-files-in-windows-7-or-8/ which still applies to W10 and W11
> 
> In the windows run box, open "gpedit.msc" as an administrator ![image](https://user-images.githubusercontent.com/4913771/145898591-9e8a4da8-f00f-4ea4-b8fe-4f0b2b1476bd.png)
> 
> Navigate to here and clear out these values ![image](https://user-images.githubusercontent.com/4913771/145898735-1babe894-0590-4efe-b15f-8b12c8ea86f1.png)

I can't see the folder that you talk
![image](https://user-images.githubusercontent.com/22783445/165751414-87bafa55-7028-456a-8925-b2e8fd4990b4.png)

**Comment by simeononsecurity** [comment]
> 
> 
> 
> > This is partially documented here https://github.com/simeononsecurity/Windows-Optimize-Harden-Debloat#additions
> > 
> > To revert the changes, you'll need to import the ADMX templates from here https://github.com/simeononsecurity/STIG-Compliant-Domain-Prep/tree/master/Files/PolicyDefinitions using this guide https://www.poremsky.com/windows/use-group-policy-admx-files-in-windows-7-or-8/ which still applies to W10 and W11
> > 
> > In the windows run box, open "gpedit.msc" as an administrator ![image](https://user-images.githubusercontent.com/4913771/145898591-9e8a4da8-f00f-4ea4-b8fe-4f0b2b1476bd.png)
> > 
> > Navigate to here and clear out these values ![image](https://user-images.githubusercontent.com/4913771/145898735-1babe894-0590-4efe-b15f-8b12c8ea86f1.png)
> 
> I can't see the folder that you talk
> ![image](https://user-images.githubusercontent.com/22783445/165751414-87bafa55-7028-456a-8925-b2e8fd4990b4.png)
> 

you'll need to import the ADMX templates from here https://github.com/simeononsecurity/STIG-Compliant-Domain-Prep/tree/master/Files/PolicyDefinitions using this guide https://www.poremsky.com/windows/use-group-policy-admx-files-in-windows-7-or-8/ which still applies to W10 and W11

**Comment by peter9811** [comment]
> > > This is partially documented here https://github.com/simeononsecurity/Windows-Optimize-Harden-Debloat#additions
> > > To revert the changes, you'll need to import the ADMX templates from here https://github.com/simeononsecurity/STIG-Compliant-Domain-Prep/tree/master/Files/PolicyDefinitions using this guide https://www.poremsky.com/windows/use-group-policy-admx-files-in-windows-7-or-8/ which still applies to W10 and W11
> > > In the windows run box, open "gpedit.msc" as an administrator ![image](https://user-images.githubusercontent.com/4913771/145898591-9e8a4da8-f00f-4ea4-b8fe-4f0b2b1476bd.png)
> > > Navigate to here and clear out these values ![image](https://user-images.githubusercontent.com/4913771/145898735-1babe894-0590-4efe-b15f-8b12c8ea86f1.png)
> > 
> > 
> > I can't see the folder that you talk
> > ![image](https://user-images.githubusercontent.com/22783445/165751414-87bafa55-7028-456a-8925-b2e8fd4990b4.png)
> 
> you'll need to import the ADMX templates from here https://github.com/simeononsecurity/STIG-Compliant-Domain-Prep/tree/master/Files/PolicyDefinitions using this guide https://www.poremsky.com/windows/use-group-policy-admx-files-in-windows-7-or-8/ which still applies to W10 and W11

I'm doing right now. But do'nt exist one script to only delete the "controls" to the Chrome/Firefox?

**Comment by peter9811** [comment]
Now I can config everything. Thanks
But maybe you can implement something to select which extensions or to what apps apply
![image](https://user-images.githubusercontent.com/22783445/165753674-81facefc-d9bd-44df-9972-aacf764e8c52.png)

**Comment by simeononsecurity** [comment]
> Now I can config everything. Thanks
> But maybe you can implement something to select which extensions or to what apps apply
> ![image](https://user-images.githubusercontent.com/22783445/165753674-81facefc-d9bd-44df-9972-aacf764e8c52.png)
> 

We appreciate the suggestion, however the configurations included in this script are based upon security and privacy industry guidance, standards, and otherwise best practices. Any diversions from the script's baseline arguably make your system less secure. With this in mind, you're always welcome to modify the script to your needs. But, making the script dynamic in the way that would be required to satisfy your request isn't in our plans as this time.
