### ISSUE TITLE
Downloads on Chrome are Failing

### ISSUE THREAD

**Issue by AadilGillani** [simeononsecurity/Windows-Optimize-Harden-Debloat#24]
Downloads on Chrome are Failing and showing a message of Failed - Blocked.
At first I thought this was due to the the file that I am downloading being malacious but after some time I noticed it is happening on every File.

![downloads_failing](https://user-images.githubusercontent.com/15800642/153386848-fff67358-b5af-46ea-a8da-aec9346657e3.PNG)
.

I tried to see some articles on the web to fix this issue but inside the security tab of inetcpl.cpl i am not being able change any settings as it is showing me a warning that some settings are being manged by your administrator
![error_internetsettings](https://user-images.githubusercontent.com/15800642/153388394-a5947bd8-d942-450a-8d3e-2f3b02634e93.PNG)

Please help me.

**Comment by simeononsecurity** [comment]
> Downloads on Chrome are Failing and showing a message of Failed - Blocked. At first I thought this was due to the the file that I am downloading being malacious but after some time I noticed it is happening on every File.
> 
> ![downloads_failing](https://user-images.githubusercontent.com/15800642/153386848-fff67358-b5af-46ea-a8da-aec9346657e3.PNG) .
> 
> I tried to see some articles on the web to fix this issue but inside the security tab of inetcpl.cpl i am not being able change any settings as it is showing me a warning that some settings are being manged by your administrator ![error_internetsettings](https://user-images.githubusercontent.com/15800642/153388394-a5947bd8-d942-450a-8d3e-2f3b02634e93.PNG)
> 
> Please help me.

So, the answer to this may be a bit technical...

Download this repo [here](https://github.com/simeononsecurity/STIG-Compliant-Domain-Prep/archive/refs/heads/master.zip)
The files you want are in ```.\Files\PolicyDefinitions\``` inside that repo. You'll want to download the entire repo and extract the zip file.
Copy the contents of that folder to C:\Windows\PolicyDefinitions\
Those are the template files you need to see the group policies that are applied.

On your system, type ```gpedit.msc``` in the search bar, run it as an administrator, and navigate to ``` Computer Settings > Administrative Templates > Google > Google Chrome > Safe Browsing Settings ```

Make the safe browsing protection level match the following
![image](https://user-images.githubusercontent.com/4913771/153525914-959835ba-6421-4104-b765-b488e5562b97.png)


If you want to change the extensions or remove them there are policies under 
``` Computer Settings > Administrative Templates > Google > Google Chrome > Extensions ``` and ``` Computer Settings > Administrative Templates > Mozilla > FireFox > Extensions ```

**Comment by simeononsecurity** [comment]
Additionally, please read https://github.com/simeononsecurity/Windows-Optimize-Harden-Debloat#additions
