### ISSUE TITLE
Window update Got Stuck 

### ISSUE THREAD

**Issue by STRK-ND** [simeononsecurity/Windows-Optimize-Harden-Debloat#27]
Window update Got Stuck & Microsoft Store Also Not Working ...

**Comment by simeononsecurity** [comment]
Windows updates aren't broken by this script. Try rebooting and try again.
For the microsoft store, what specific issue are you running into?

Please see the following for the store: https://github.com/simeononsecurity/Windows-Optimize-Harden-Debloat/issues/22
https://github.com/simeononsecurity/Windows-Optimize-Harden-Debloat/issues/19
