### ISSUE TITLE
Audio render error on browser

### ISSUE THREAD

**Issue by bilsby** [simeononsecurity/Windows-Optimize-Harden-Debloat#28]
Are you aware of audio render error on chrome browser after installing the script?

**Comment by simeononsecurity** [comment]
> Are you aware of audio render error on chrome browser after installing the script?

We've not heard any reports involving audio render issues. Can you provide more details?

**Comment by simeononsecurity** [comment]
> Wondering if any policy could be blocking streaming video and how to
Running a fresh W10 vm with our configuration script, we were unable to recreate your error.  Our recommendation is to reinstall windows, make sure your drivers are up to date, and try again.
![image](https://user-images.githubusercontent.com/4913771/164309096-07bbdf8f-6329-443e-907e-3bebc9fe620f.png)
