### ISSUE TITLE
Unblock Microsoft Store

### ISSUE THREAD

**Issue by testdriver87** [simeononsecurity/Windows-Optimize-Harden-Debloat#31]
Hi,
How can I unblock Microsoft Store?

**Comment by simeononsecurity** [comment]
https://github.com/simeononsecurity/Windows-Optimize-Harden-Debloat/issues/16
https://github.com/simeononsecurity/Windows-Optimize-Harden-Debloat/issues/22
https://github.com/simeononsecurity/Windows-Optimize-Debloat/issues/1
