### ISSUE TITLE
Easy Anti Cheat

### ISSUE THREAD

**Issue by NSAInside** [simeononsecurity/Windows-Optimize-Harden-Debloat#43]
Hi simeononsecurity,

When playing Easy Anti Cheat (https://easy.ac) enabled games, the game will crash after using this script.
If you restore and try and run an EAC enabled game, no issues.

tested on fresh windows installation, unable to locate the issue.
a dump file was generated which i've attached.

In this case, it was tested with Rust (rust.facepunch.com)

[RustClient.exe.9756.zip](https://github.com/simeononsecurity/Windows-Optimize-Harden-Debloat/files/9742662/RustClient.exe.9756.zip)

**Comment by simeononsecurity** [comment]
@NSAInside 
Hi there, it's unfortunate you ran into an issue using our script.
We previously tested EAC while development of it and have just completed additional testing.
We were unable to replicate the issues you experienced on Rust, 7D2D, and Fall Guys.  While we don't directly support any of these games, we're not trying to break them either. 

Can you provide any more information about your systems configuration? Also what were the exact steps you performed?

**Comment by simeononsecurity** [comment]
@NSAInside Any updates? 7 More days and we will close this issue as resolved.
