### ISSUE TITLE
Suggest disabling TLS 1.0 (comment it out). line 533

### ISSUE THREAD

**Issue by GitFezz** [simeononsecurity/Windows-Optimize-Harden-Debloat#51]
On line 533 of project [Windows-Optimize-Harden-Debloat](https://github.com/simeononsecurity/Windows-Optimize-Harden-Debloat), i see we're enabling TLS 1.0.  I'd recommend disabling it as even NIST is not supporting it any longer due to security concerns.

"The Internet Engineering Task Force found vulnerabilities in TLS 1.0, one of the most widely used protocols, and updated it to TLS 1.1 and then TLS 1.2 to resolve many of these security issues. In order to mitigate these vulnerabilities and conform to our own recommendations, NIST will disable the use of TLS 1.0 for connections to our public website. "

https://www.nist.gov/oism/tls-10-being-turned-wwwnistgov

**Comment by simeononsecurity** [comment]
> On line 533 of project [Windows-Optimize-Harden-Debloat](https://github.com/simeononsecurity/Windows-Optimize-Harden-Debloat), i see we're enabling TLS 1.0. I'd recommend disabling it as even NIST is not supporting it any longer due to security concerns.
> 
> "The Internet Engineering Task Force found vulnerabilities in TLS 1.0, one of the most widely used protocols, and updated it to TLS 1.1 and then TLS 1.2 to resolve many of these security issues. In order to mitigate these vulnerabilities and conform to our own recommendations, NIST will disable the use of TLS 1.0 for connections to our public website. "
> 
> https://www.nist.gov/oism/tls-10-being-turned-wwwnistgov

@GitFezz Trust me, we're tracking. However, you'd be surprised how many applications rely on TLS 1.0 connections still. When we were applications such as Battle.Net, Steam, etc. were no longer working in some form. We're unsure if it's how windows is implementing said change or if those applications genuinely rely on them. In the browsers we also opted to not disable TLS 1.0 for similar reasons such as it breaking a lot of websites and self hosted applications. The goal here was to harden systems as best as possible while breaking as little as possible.  It's easy to change the two values needed to disable TLS 1.0 if you wish. But unfortunately it was just not feasible for our workflow or the majority of the public.

**Comment by GitFezz** [comment]
Understood.  Thanks for the reply and explanation!  Big fan of the work you've done here!
