### ISSUE TITLE
Can't update windows / some applications are saying im offline and i need to connect to internet

### ISSUE THREAD

**Issue by BehaDev** [simeononsecurity/Windows-Optimize-Harden-Debloat#56]
Hello , after using the script i've had multiple bugs like im not able to update the windows / some applications ( for exp nvidia drivers / EA app...)  its a firewall bug for sure , most of those are notifing me as i need to connect to internet while i'am already , i would be grateful if there is a fix for this. Thank you.

**Comment by simeononsecurity** [comment]
The updates that windows updates install for nvidia are generally outdated. 
Please install nvidia drivers manually. https://www.nvidia.com/download/index.aspx
Drivers updating from windows update is disabled per STIG. This is documented in the readme.

As far as the EA app having issues, can you provide more information?
Thanks!

**Comment by BehaDev** [comment]
Thanks for the quick reply , when i try to open a game using EA launcher , it says 'ea error we ve noticed your computer is currently offline' other launchers are working , noticed the same error as the windows update :" We couldn't connect to the update service. We'll try again later, or you can check now. If it still doesn't work, make sure you're connected to the Internet." Means STIG is touching more parts than it should be , and sadly my PC didnt create a restore point for some reason , any fixes available ? Thanks again.

**Comment by simeononsecurity** [comment]
It should've captured a restore point.
```powershell
# if any parameters are set to true take a restore point
$date = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
$scriptName = $MyInvocation.MyCommand.Name
if ($paramscheck | Where-Object { $_ } | Select-Object) {
    $freespace = (Get-WmiObject -class Win32_LogicalDisk | Where-Object { $_.DeviceID -eq 'C:' }).FreeSpace
    $minfreespace = 10000000000 #10GB
    if ($freespace -gt $minfreespace) {
        Write-Host "Taking a Restore Point Before Continuing...."
        $job = Start-Job -Name Take Restore Point -ScriptBlock {
            New-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows NT\CurrentVersion\SystemRestore' -Name 'SystemRestorePointCreationFrequency' -PropertyType DWORD -Value 0 -Force
            Checkpoint-Computer -Description "RestorePoint $scriptName $date" -RestorePointType "MODIFY_SETTINGS"
        }
        Wait-Job -Job $job
    }
    else {
        Write-Output "Not enough disk space to create a restore point. Current free space: $(($freespace/1GB)) GB"
    }
}
```

**Comment by simeononsecurity** [comment]
> Thanks for the quick reply , when i try to open a game using EA launcher , it says 'ea error we ve noticed your computer is currently offline' other launchers are working , noticed the same error as the windows update :" We couldn't connect to the update service. We'll try again later, or you can check now. If it still doesn't work, make sure you're connected to the Internet." Means STIG is touching more parts than it should be , and sadly my PC didnt create a restore point for some reason , any fixes available ? Thanks again.

It could possibly be due to some encryption settings. We'll test it. Give us a little bit to confirm.
Origin is incredibly buggy and not coded well. It breaks often, even outside of our scripts and configurations.

**Comment by BehaDev** [comment]
> It should've captured a restore point this is inside of the script. It runs by default.
> 
> ```powershell
> # if any parameters are set to true take a restore point
> $date = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
> $scriptName = $MyInvocation.MyCommand.Name
> if ($paramscheck | Where-Object { $_ } | Select-Object) {
>     $freespace = (Get-WmiObject -class Win32_LogicalDisk | Where-Object { $_.DeviceID -eq 'C:' }).FreeSpace
>     $minfreespace = 10000000000 #10GB
>     if ($freespace -gt $minfreespace) {
>         Write-Host "Taking a Restore Point Before Continuing...."
>         $job = Start-Job -Name Take Restore Point -ScriptBlock {
>             New-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows NT\CurrentVersion\SystemRestore' -Name 'SystemRestorePointCreationFrequency' -PropertyType DWORD -Value 0 -Force
>             Checkpoint-Computer -Description "RestorePoint $scriptName $date" -RestorePointType "MODIFY_SETTINGS"
>         }
>         Wait-Job -Job $job
>     }
>     else {
>         Write-Output "Not enough disk space to create a restore point. Current free space: $(($freespace/1GB)) GB"
>     }
> }
> ```
I confirm that , but seems i can't find it somehow.

**Comment by BehaDev** [comment]
> > Thanks for the quick reply , when i try to open a game using EA launcher , it says 'ea error we ve noticed your computer is currently offline' other launchers are working , noticed the same error as the windows update :" We couldn't connect to the update service. We'll try again later, or you can check now. If it still doesn't work, make sure you're connected to the Internet." Means STIG is touching more parts than it should be , and sadly my PC didnt create a restore point for some reason , any fixes available ? Thanks again.
> 
> It could possibly be due to some encryption settings. We'll test it. Give us a little bit to confirm. Origin is incredibly buggy and not coded well. It breaks often, even outside of our scripts and configurations.

EA application is the new origin launcher , and yes it breaks very often, it would be helpful if there is a fix ill be up for updates , Thanks.

**Comment by simeononsecurity** [comment]
> EA application

We were able to replicate the issue.
The EA Logs don't provide anything to go off of however.
You can go to the following folder on windows %localappdata%\Electronic Arts\EA Desktop\Logs

**Comment by simeononsecurity** [comment]
We were able to get in by unchecking the "keep me signed in" option. Try that and report back @BehaDev

**Comment by BehaDev** [comment]
The error still occurs , here is a screenshot of the error im getting https://preview.redd.it/zg8rukdu8yr71.png?width=412&format=png&auto=webp&v=enabled&s=1d33ab2eff8ad389d635727887ee55b5ade2515c 

as i look through the problem seems its related to firewall as someone is refeering to the problem in reddit with this comment " I was having the same issue because PiHole (or something else on the network like firewall or even your ISP) was blocking access to "proxy.novafusion.ea.com" - apparently this is needed for connection. "

**Comment by simeononsecurity** [comment]
> The error still occurs , here is a screenshot of the error im getting https://preview.redd.it/zg8rukdu8yr71.png?width=412&format=png&auto=webp&v=enabled&s=1d33ab2eff8ad389d635727887ee55b5ade2515c
> 
> as i look through the problem seems its related to firewall as someone is refeering to the problem in reddit with this comment " I was having the same issue because PiHole (or something else on the network like firewall or even your ISP) was blocking access to "proxy.novafusion.ea.com" - apparently this is needed for connection. "

We're still looking into the issue. But the bug seems to be on ea's side of things. 
We don't block any DNS or IP's in this script that pertain to EA or Origin. So we're unsure what the issue is unfortunately.
Though we have reported our findings and logs to EA. hopefully they can come up with a fix.

We'll leave the issue open. But from our investigation there doesn't seem like there is anything we can do.

**Comment by BehaDev** [comment]
Reset this pc option in windows 11 may reset the script ?

**Comment by simeononsecurity** [comment]
> Reset this pc option in windows 11 may reset the script ?

Assuming you don't have a restore point, you're going to need to reinstall your operating system. To truely reset everything.
It's unfortunate, but the windows reset option doesn't actually reset everything. 
Make sure you have backups of any important files before trying to do any reset or reinstall.


https://simeononsecurity.ch/articles/how-to-install-windows-10-and-windows-11-from-scratch/

**Comment by BehaDev** [comment]
Media tool for windows 11 seems to give an error when opening it since its related to windows update , can't open it and create an bootable usb.

**Comment by simeononsecurity** [comment]
> Media tool for windows 11 seems to give an error when opening it since its related to windows update , can't open it and create an bootable usb.

You'll have to do this from a separate machine. Or following doing a reset of the same pc.
