### ISSUE TITLE
Cant sign in

### ISSUE THREAD

**Issue by Lenny-cmd** [simeononsecurity/Windows-Optimize-Harden-Debloat#57]
What is the default password, I used this thinking it was a windows optimizer and now I am locked out of my pc. Please help me, it will koe let me rest my windows

**Comment by simeononsecurity** [comment]
@Lenny-cmd 
I'm sorry you're running into issues.
Did you read the readme? https://github.com/simeononsecurity/Windows-Optimize-Harden-Debloat#notes-warnings-and-considerations
