### ISSUE TITLE
GPO Update not completing

### ISSUE THREAD

**Issue by jacoballison** [simeononsecurity/Windows-Optimize-Harden-Debloat#58]
When running this script on a fresh install of 22H2, GPO updates are not processing with the following errors:

```
Performing Group Policy Update
Updating policy...
Computer Policy update has completed successfully.
The following warnings were encountered during computer policy processing:
Windows failed to apply the Group Policy Scheduled Tasks settings. Group Policy Scheduled Tasks settings might have its own log file. Please click on the "More information" link.
User Policy update has completed successfully.
The following warnings were encountered during user policy processing:
Windows failed to apply the Group Policy Registry settings. Group Policy Registry settings might have its own log file. Please click on the "More information" link.
For more detailed information, review the event log or run GPRESULT /H GPReport.html from the command line to access information about Group Policy results.
WARNING: A reboot is required for all changed to take effect
```

Attached is a copy of the GP Report, with identifying information redacted.

Of note, Bitlocker setup fails following running the script, although I think that's because the group policy fails.

[GPReport.pdf](https://github.com/simeononsecurity/Windows-Optimize-Harden-Debloat/files/11367487/GPReport.pdf)

**Comment by jacoballison** [comment]
Tracked this down a bit better, it points to the schedule updates xml file. If Windows updates tweaks are commented out or unchecked there are no issues. Likewise, this same bug exists in the optimize/debliat script which uses the same XML.

**Comment by simeononsecurity** [comment]
> Tracked this down a bit better, it points to the schedule updates xml file. If Windows updates and the Internet Explorer tweaks are commented out or unchecked there are no issues updating group policy. Haven't checked to see if there are any bit locker issues when the updates tweak has been unchecked. Likewise, this same bug exists in the optimize/debliat script which uses the same XML.

This is a great find! We will look into and attempt to fix this shortly.
