### ISSUE TITLE
How do I revert

### ISSUE THREAD

**Issue by Ferosauce** [simeononsecurity/Windows-Optimize-Harden-Debloat#6]
hi i used it and it removed the built in administrator account which had the system restore point now i cant use systemrestore pls help

**Comment by simeononsecurity** [comment]
It didn't remove the built in admin account. It only disabled it per [Windows 10 V2R1](https://dl.cyber.mil/stigs/zip/U_MS_Windows_Defender_Antivirus_V2R1_STIG.zip).

![image](https://user-images.githubusercontent.com/4913771/108644747-36f0a380-74a8-11eb-8b8f-29a795438e99.png)
![image](https://user-images.githubusercontent.com/4913771/108644756-453ebf80-74a8-11eb-954a-d9982cbfe1e1.png)
Change this to enabled.
![image](https://user-images.githubusercontent.com/4913771/108644764-4f60be00-74a8-11eb-89e5-37faf39df1ab.png)

**Comment by simeononsecurity** [comment]
That account isn't used by default on most systems. It shouldn't break anything to have this policy enabled.

Can you tell me what exactly is broken?

**Comment by simeononsecurity** [comment]
Are you still having problems @Ferosauce ?

**Comment by simeononsecurity** [comment]
Closing due to lack of response and due to configuration being documented..
