### ISSUE TITLE
Revert 

### ISSUE THREAD

**Issue by flairlysea** [simeononsecurity/Windows-Optimize-Harden-Debloat#62]
There should be a revert button

**Comment by simeononsecurity** [comment]
> There should be a revert button

Reverting isn't as simple as just a button. Unfortunately windows does not have a boolean state system. This means we'd have to store both the desired state and its previous state each time before running. This would become incredibly problematic to manage, especially accounting for users who may run the script multiple times. So unfortunately we don't see a "revert" button as a feasible option both now and in the future.

The script does capture a restore point prior to running however.
Please refer to Microsoft's documentation on the matter if you're unaware how to perform a system restore
https://support.microsoft.com/en-us/windows/use-system-restore-a5ae3ed9-07c4-fd56-45ee-096777ecd14e

If you're having any specific issues however, we'd be glad to discuss and help you fix them. Please just update us here.

**Comment by simeononsecurity** [comment]
@flairlysea 
Any updates? 
If not, we're going to mark the ticket as closed. Please respond.

**Comment by dougg0k** [comment]
A revert does not necessarily need to be a toggle. You can have both options. A revert could be just to apply values that are the default.

You could still get each value from the changed ones, as to revert only them to default value, but still, it's a choice. I suppose having a place like a json with changed value and default value or whatever, could be another option.

**Comment by dougg0k** [comment]
It make sense, regardless, it was a choice to do or not.
