### ISSUE TITLE
 Issue with Persistent Registry Value Changes upon System Reboot

### ISSUE THREAD

**Issue by puneetred** [simeononsecurity/Windows-Optimize-Harden-Debloat#65]
I am experiencing an issue with persistent registry value changes upon system reboot. Specifically, I am attempting to enable developer tools in Google Chrome by modifying the registry key located at `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome\DeveloperToolsAvailability` to a value of `1`. However, after each system reboot, the value consistently reverts back to 2.

This behavior is not limited to Google Chrome; I have observed similar occurrences with other registry changes as well.

**Comment by simeononsecurity** [comment]
> I am experiencing an issue with persistent registry value changes upon system reboot. Specifically, I am attempting to enable developer tools in Google Chrome by modifying the registry key located at `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome\DeveloperToolsAvailability` to a value of `1`. However, after each system reboot, the value consistently reverts back to 2.
> 
> This behavior is not limited to Google Chrome; I have observed similar occurrences with other registry changes as well.

This is because that setting is set using group policies 
Follow the instructions here https://github.com/simeononsecurity/Standalone-Windows-STIG-Script#editing-policies-in-local-group-policy-after-the-fact
