### ISSUE TITLE
Cannot log in after installing the script

### ISSUE THREAD

**Issue by x5h4r7h0k** [simeononsecurity/Windows-Optimize-Harden-Debloat#66]
**Describe the bug**
installed the script , i was logged in with my microsoft account. after reboot pc is asking for user and password. since it disabled my microsoft acount, i cannot log in.

**Comment by simeononsecurity** [comment]
> **Describe the bug** installed the script , i was logged in with my microsoft account. after reboot pc is asking for user and password. since it disabled my microsoft acount, i cannot log in.

Please read the readme next time

https://github.com/simeononsecurity/Windows-Optimize-Harden-Debloat#notes-warnings-and-considerations
