### ISSUE TITLE
PC goes into lockscreen after 2 minutes of inactivity

### ISSUE THREAD

**Issue by Lightningblade** [simeononsecurity/Windows-Optimize-Harden-Debloat#69]
I can't find the option that set or enabled this in the scripts.
My problem is that I don't know how to adjust the time (Its not in Power Options / Power and sleep settings).
The 2 minutes are a problem because it just locks my PC when i read an article or look at a gif the like.

Sorry for not looking thoroughly enough at all scripts but maybe someone knows the correct setting.

**Comment by simeononsecurity** [comment]
> I can't find the option that set or enabled this in the scripts.
> My problem is that I don't know how to adjust the time (Its not in Power Options / Power and sleep settings).
> The 2 minutes are a problem because it just locks my PC when i read an article or look at a gif the like.
> 
> Sorry for not looking thoroughly enough at all scripts but maybe someone knows the correct setting.

It shouldn't be 2 minutes. It's explicitly set to 15 minutes per the configuration guidelines defined in the readme. If it is locking faster than that, your machine has additional issues.

**Comment by simeononsecurity** [comment]
Please fill out the exact commands you used to run the script. There are multiple configurations based on how you launched it.

**Comment by simeononsecurity** [comment]
@Lightningblade 

Please try the following to resolve your issue. 


```powershell
$timeout = 15
$regPath = "HKCU\Control Panel\Desktop"
$regName = "ScreenSaveTimeout"
$regValue = ($timeout * 60)

# Set lock screen timeout using powercfg
$guid = (powercfg -q | Select-String '.*(GUID:.*)' | Out-String).Trim()
powercfg -setacvalueindex $guid SUB_VIDEO VIDEOCONLOCK $timeout
powercfg -setdcvalueindex $guid SUB_VIDEO VIDEOCONLOCK $timeout

# Set lock screen timeout using reg.exe
reg.exe add "$regPath" /v "$regName" /t REG_SZ /d "$regValue" /f
```

**Comment by Lightningblade** [comment]
I used the GUI with all option enabled.

The script has problems with the parameters for powercfg. $guid was empty when outputting it.

I just reinstalled Windows now since you said my PC has other problems. Thank you for your help.
