### ISSUE TITLE
SOS script wil not allow office 365 products to open.

### ISSUE THREAD

**Issue by midnightblue1122** [simeononsecurity/Windows-Optimize-Harden-Debloat#7]
Windows 10 Pro 2004. After applying sos-optimize-windows.ps1 script, all Microsoft Office products no longer open. Office reinstall does not clear up the problem

SOS script will not allow office 365 products to open. No error messages, no event logs, nothing.

Issue confirmed with non-365 versions as well.

WINWORD exe gives an "Windows cannot access the specified device, path, or file. You may not have the appropriate permissions to access this item."

Office is install on the C: system drive, happens with other OFFICE exe's as well.

I would also like to add that I appreciate your hard work on this. This is an amazing tool.

**Comment by simeononsecurity** [comment]
Recreating the details you specified, W10 Pro 2004 with O365/Standard variants of Office, I was unable to replicate your issue.  

![image](https://user-images.githubusercontent.com/4913771/109358202-4a6e8680-787b-11eb-879e-ef7259cd562f.png)

Can you provide any additional details? If this is a widespread issue, I'd love to solve it.
Did you run this on a fresh install of windows? 
Are you domain joined? If so, could their have been any competing GPO's applied? 
It may be possible that Office was installed in your Appdata folder relative to your user account.
The applocker policies can block this. Try specifically running the office installer as an administrator.

**Comment by simeononsecurity** [comment]
@midnightblue1122 Can you provide more information?

Since I can not replicate your results and you haven't replied, I'll be forced to close this issue. I'll give it 3 more days.

**Comment by simeononsecurity** [comment]
Issue closed. No user response. Unable to replicate issue.
