### ISSUE TITLE
Edge Auto Delete History

### ISSUE THREAD

**Issue by truongvu2k1** [simeononsecurity/Windows-Optimize-Harden-Debloat#71]
Hi Simone, I really like and very thanks your scripts, but I have problem with edge cookie, how to turn off auto delete cookie and history in edge. Many thanks.

**Comment by simeononsecurity** [comment]
> Hi Simone, I really like and very thanks your scripts, but I have problem with edge cookie, how to turn off auto delete cookie and history in edge. Many thanks.

Follow the instructions here
https://github.com/simeononsecurity/Windows-Optimize-Harden-Debloat#editing-policies-in-local-group-policy-after-the-fact
under Computer Settings > Administrative Templates > Microsoft Edge you'll find all the settings you're looking for
