### ISSUE TITLE
Can't apply group policy if install offline

### ISSUE THREAD

**Issue by truongvu2k1** [simeononsecurity/Windows-Optimize-Harden-Debloat#72]
I have problem when use your script offline, but when I install online automatic, it is no problem
Windows failed to apply the Group Policy Registry settings. Group Policy Registry settings might have its own log file. Please click on the "More information" link.

**Comment by simeononsecurity** [comment]
> I have problem when use your script offline, but when I install online automatic, it is no problem Windows failed to apply the Group Policy Registry settings. Group Policy Registry settings might have its own log file. Please click on the "More information" link.
@truongvu2k1 
That isn't exclusive to it being offline. For now that is an expected error.
it has to do with a couple of the gpos being applied in a non domain environment. These can be safely ignored for now. 
We're working on a fix.

**Comment by truongvu2k1** [comment]
thanks so much
