### ISSUE TITLE
Allow downloads from the store ( installing ubuntu issue )

### ISSUE THREAD

**Issue by Khwarazmi** [simeononsecurity/Windows-Optimize-Harden-Debloat#8]
Hello,
is there is any way to allow downloads from microsoft store ?
I'm trying to install ubuntu because I'm using wsl2 but i cannot download anything from the store
and i manually downloaded Ubuntu but when i click on it nothing happens at all

**Comment by simeononsecurity** [comment]
@Khwarazmi This is a known issue. Please be aware. 
Read https://github.com/simeononsecurity/Windows-Optimize-Debloat/issues/1 for the fix.

**Comment by Khwarazmi** [comment]
@simeononsecurity that fixed the issue thank you so much
