### ISSUE TITLE
Cannot setup Proton Mail Bridge with Outlook

### ISSUE THREAD

**Issue by panzer-arc** [simeononsecurity/Windows-Optimize-Harden-Debloat#80]
**Describe the bug**
Proton Mail Bridge appears to use a self-signed certificate, which I think is the issue here. I believe this series of tweaks stops this program from working with Outlook. I'm wondering if anyone can offer a workaround. I don't believe this is an 'insecure' way to access emails, but it is necessary with the way Proton implements their service.

**To Reproduce**
1. Add a new account in outlook
2. Copy data from Proton Bridge to Outlook forms
3. Receive error "We couldn't connect to the outgoing SMTP server. The connection timed out."

**Expected behavior**
You should be able to add the protonmail account to Outlook.

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise 22H2

**Additional context**
This article describes the process in detail
https://proton.me/support/protonmail-bridge-clients-windows-outlook-2019

**Comment by simeononsecurity** [comment]
I will say this isn't a configuration we test for. However, we just tested it following the guide linked and it worked perfectly for us.
Be sure you specify the correct ports and encryption settings. Additionally you can add the certificate to the trusted store on windows if that error pops up. @panzer-arc

**Comment by panzer-arc** [comment]
Thanks for trying at least. I will have to dig deeper when I have more time. I suppose this could be some other type of network issue.
