### ISSUE TITLE
after running script defender is broken and inaccessible even after full reset.

### ISSUE THREAD

**Issue by MichaelYelavich** [simeononsecurity/Windows-Optimize-Harden-Debloat#83]
**Describe the bug**
Defender is irreparably broken after script use.

**To Reproduce**
Run the script, reinstall windows, try to run defender

**Expected behavior**
Defender runs as expected OOTB

**Comment by simeononsecurity** [comment]
> **Describe the bug** Defender is irreparably broken after script use.
> 
> **To Reproduce** Steps to reproduce the behavior: Run the script, reinstall windows, try to run defender
> 
> **Expected behavior** Defender runs as expected OOTB

Certainly! It's important to gather more information to understand and address the issue. Here's a reply you can use:

@MichaelYelavich ,

Thank you for bringing this to our attention. I appreciate your feedback and I'm here to help resolve the issue you're experiencing. However, to assist you better, I'll need some additional information. The provided details are a bit sparse, so let's try to narrow down the problem.

1. Could you provide more details on how Defender is behaving after running the script? Are there any error messages or specific issues you encounter?

2. Are there any specific configurations or options you used with the script that might be relevant to this problem?

3. Can you share more about the environment in which you are running the script? For instance, the Windows version, architecture (32-bit or 64-bit), and any other relevant system information such as the Windows Build Number, Version, and Edition.

4. Have you encountered any other issues with Windows Defender before using the script?

5. Did you follow any additional steps after reinstalling Windows that might be affecting Defender?

The more details you can provide, the better we can investigate and address the issue. If possible, screenshots or logs related to the problem would be immensely helpful.

I'm committed to resolving this and appreciate your cooperation in providing the necessary information.

Best,
@simeononsecurity

**Comment by MichaelYelavich** [comment]
@simeononsecurity 

Sorry for the shitty report, i was much to tired to be making github posts

Heres the message

Page not available.

Your IT administrator has limited access to some areas of this app. And the item you tried to access is not available. Contact your IT helpdesk for more information. 

What i have tried:

Reset

Cloud reset

Iso reset

Clear registry

Delete windows code integrity files.

Windows 11 Pro 64bit 22H2

AMD Ryzen 5 Pro 7540U

**Comment by MichaelYelavich** [comment]
Oh and if it helps, i used the one click enable everything on the script. I'm also using a local account. The only modifications I made myself was gutting telemetry via gpedit.msc and services.msc but that shouldn't effect this as it didn't do anything of the sort before I ran your program. I could be wrong and am excited to learn as I'm a linux guy and am only using windows for college and this is just one of many things that makes me regret this.

**Comment by simeononsecurity** [comment]
@MichaelYelavich 

We ran more tests to confirm. But no our script isn't doing what you're talking about.
Defender opens and works just as expected. Even on our Windows 11 Pro 64bit 22H2 test system we just created.
Something you must've changed affected this.
