### ISSUE TITLE
How to Undo the changes

### ISSUE THREAD

**Issue by lokesh7suman** [simeononsecurity/Windows-Optimize-Harden-Debloat#84]
if i made changes with this Windows-Optimize-Harden-Debloat
how can i revert those changes.

**Comment by simeononsecurity** [comment]
@lokesh7suman 

https://github.com/simeononsecurity/Windows-Optimize-Harden-Debloat/discussions/61#discussioncomment-6256730

**Comment by simeononsecurity** [comment]
https://github.com/simeononsecurity/Windows-Optimize-Harden-Debloat/wiki/How-to-Reverse-the-Changes-performed-in-Windows%E2%80%90Optimize%E2%80%90Harden%E2%80%90Debloat
