### ISSUE TITLE
Help me fix my pc X_Admin account took over system

### ISSUE THREAD

**Issue by NioKing77** [simeononsecurity/Windows-Optimize-Harden-Debloat#87]
**Locked out of my user. X_Admin in its  place**
Hello I runned the script with all selected in my normal pc. I didn't know I had to create a new organization or something as I later read in the instructions. 
I tried fixing it by running safe mode with network setrings on. And the admin user got overridden by x_admin. Now everything run from diks partition x/windows/system32. And i can't do anything. Can't login. Can't factory reset my pc, because the user x persists. It got eeally really screwed and I'm scared. Please help me. Instruct on how ro recover my pc. I'm beggin you.

**To Reproduce**
1. Run the script all settings on
2. Restart pc
3. Try logging in. Credentials verification failed.
4. Run safe mode with nerwork settings on.
5. Logs in as User X
6. Try factory resseting user trough safe mode.
7. Pc restarts and user x is still there.
8. Can't login as I don't have the password.

**Expected behavior**
Obshould lofin and see my pc files and programs without issue.

I just want to delete it please. I want my pc to be normal again. I'm sorry for being such and ignorant and have runned the script without knowing what it does. I'm sorry. Bur please. I know there must be a way to fix this. 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by NioKing77** [comment]
Resetting the pc is the only way to fix it. At least from my end. It must be hard resetting. My settings are in spanish. 
But in translation the reset settings you should pick are: from local device. Reset everything. No need to delete all partitions. Just everything from windows installation partition. Then wait until your pc installs windows. Set it up. I created a new outlook account just in case. And now Im finally in. Lost all apps. But hey, I can use my pc now so that's good.

More in depth guide would be like this:
1. Force entering safe mode in your pc. To do this you must turn it on, wait until you see the loading wheel of windows and then press the physical power button in your pc and wait until it shuts down. 

Do this two times or until you see Automatic Repair Initiation. By waiting in automatic repair, you'll get into safe mode.

Then go to advanced settings menu. And reset your pc. There you will find the options mentioned before. Please, don't panick if you restart your pc and x_admin is still there. Just try again with the seetings I mentioned preferably. As that worked for me.
I also had to do it 2 times. First time I tried resseting windows from the internet download reset option. That did not work. So, local reset option was my salvation. Then just be prepared to reinstall everything. Take it as the start of a new life.

To avoid this issue read the warnings before running this script. It is probably not for normal people that does office job like me. It is for a more hardcore public. I bet this is some secret agent level protection that most of us don't need. So, please be careful. I was able to fix it but as mentioned, sacrifices were made. Lost some projects and such.

And the reason I got here was by accident. In a written guide by Chris Titus Tech. In the first comment's answer were titus tech left the links for this github repository. 

If you are here and are a casual optimization enjoyer, don't try this. 

If you find yourself somehow in a similar situation, don't panick. Reset your pc. Or wait until devs share a different solution or maybe not, in which case follow this attempt of a guide.

**Comment by simeononsecurity** [comment]
> Sorry to ask this, but I have one last question. Is x_admin intended to be a thing created by the script as a security measure? Or was my pc in deep troubles without me noticing? I don't think so, as it happened after running the script and restarting the pc. Just curious. Thank you.

@NioKing77 You shouldn't be using the build int administrator account at all.
It is renamed and disabled so that it is more recognizable if it is ever enabled and used.
This is mentioned in the top of the readme for this repo.

FOR EXAMPLE, THE FOLLOWING WILL BREAK IF YOU RUN THIS WITHOUT TAKING PREVENTATIVE STEPS:

    Using the default administrator account named "Administrator" is disabled and renamed per DoD STIG

        Does not apply to the default account created but does apply to using the Default Administrator account often found on Enterprise, IOT, and Windows Server Versions

        Create a new account under Computer Management and set it as an administrator if you wish. Then copy the contents of the previous users folder into the new one after signing into the new user for the first time to work around this prior to running the script.
        
  If you're not using the default administrator account, the renaming of the account and disabling of it should affect 0 things outside of the change itself. If it does, it's because either you or someone else configured your system to do so. That is not the default configuration of windows.

**Comment by simeononsecurity** [comment]
We appreciate your concern, but maybe next time read the dang readme...
