### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by SuperJakov** [simeononsecurity/Windows-Optimize-Harden-Debloat#89]
**Describe the bug**
My computer had user named after my name and it was admin with no password. That was the only user on my pc. After running the script and restarting the computer, That user no longer exists and now I have to login into "Other user", with password or pin, but I can't because I don't know password.

**Expected behavior**
After restarting it should work correctly.

**Screenshots**
![20240403_114512.jpg](https://github.com/simeononsecurity/Windows-Optimize-Harden-Debloat/assets/140004250/f4952236-b973-4f64-884d-184966ebc157)

**Desktop :**
 - OS: Windows 11 Home 23H2
 - Browser: Firefox,chrome and edge are downloaded

**Additional context**
**I was using GUI version.**
Do I have to reinstall windows? Will I lose my data?

**Comment by SuperJakov** [comment]
Fixed it.

**Comment by simeononsecurity** [comment]
@SuperJakov 
Please next time take care to read the readme before running random scripts on the internet.
