### ISSUE TITLE
Automated Install results in 503

### ISSUE THREAD

**Issue by reaseno** [simeononsecurity/Windows-Optimize-Harden-Debloat#9]
If I do:
`iwr -useb 'https://simeononsecurity.ch/scripts/windowsoptimizeandharden.ps1'|iex`

I get a remote server error with 503. Is it maybe because of the use of Cloudflare?

What I also don't understand is the explanation: "script may be launched from the extracted GitHub download"

For me it seems the script is downloading and extracting the package from GitHub itself. So why is a download needed before starting the script?

**Comment by simeononsecurity** [comment]
@reaseno 

The automated install works fine for me. Tested on PS v5 and v7 on the three most recent major versions of Windows 10. 
It's possible you are being rate limited or it was just a temporary glitch on GitHub's side of things.

The Automated install downloads the latest version of the script from GitHub, extracts the zip file, and runs the script. The script has supporting files, quite a few in fact, that are required for the script to run. It isn't feasible to run these directly from GitHub. 
The automated script is just an easier way to run it without having to download it and extract it manually.

**Comment by simeononsecurity** [comment]
You can see the script that is run [here](https://github.com/simeononsecurity/simeononsecurity.ch/blob/master/static/scripts/windowsoptimizeandharden.ps1)

**Comment by reaseno** [comment]
Using of the command  isnot possible because of cloudflare I think, which is always checking and allowing access after a while when opening the link within a browser. So I don't know why the command should work then. My suggestion would be to use the github link to the script for the command. At least that works for me.

And I wanted to say that the description in your readme is misleading, as it says that it may need to be downloaded and unzipped manually before doing the auto install command:
"script may be launched from the extracted GitHub download"

**Comment by simeononsecurity** [comment]
Fair enough, I've changed the language for the automated install. https://github.com/simeononsecurity/Windows-Optimize-Harden-Debloat/commit/5ac8c0b6fb0fe9a0cf75405b834465e057f7fec1

As far as you getting 503 errors while running the automated one-liner, I won't lax my security rules to fix it for one person.
You'll have to use the manual instructions.

**Comment by reaseno** [comment]
No, as I said, the github link works. So you could replace that link.

**Comment by simeononsecurity** [comment]
This isn't an issue. The blocks on the simeononsecurity.ch site are intentional. 
Please use the manual option.
