### ISSUE TITLE
Firefox plug-in version is too old

### ISSUE THREAD

**Issue by S0Yn** [simeononsecurity/Windows-Optimize-Harden-Debloat#91]
Can it be changed to update the best version of the xpi file? Or can it be automatically updated to grab a better version? This version of uBlock cannot block ads.

**Comment by simeononsecurity** [comment]
@S0Yn 
You can follow these instructions
https://github.com/simeononsecurity/Windows-Optimize-Harden-Debloat/wiki/Script-Customization

And go to the firefox gpo settings and enable "auto update extensions" if you'd like that feature back.
