### ISSUE TITLE
HELLPP

### ISSUE THREAD

**Issue by lethiferal** [simeononsecurity/Windows-Optimize-Harden-Debloat#93]
I can't log in to my pc anymore, it says we are unable to connect right now, please check the network and try again later. Im so afraid I can't access my pc anymore 😭

**Comment by lethiferal** [comment]
Thankfully I has a system restore 😮‍💨

**Comment by simeononsecurity** [comment]
@lethiferal 

Please consult the wiki and readme before running random scripts on the internet.

https://github.com/simeononsecurity/Windows-Optimize-Harden-Debloat/wiki/How-to-Reverse-the-Changes-performed-in-Windows%E2%80%90Optimize%E2%80%90Harden%E2%80%90Debloat
