### ISSUE TITLE
Bitlocker requiring recovery key, and bitlocker password changed (possibly?)

### ISSUE THREAD

**Issue by Run6666** [simeononsecurity/Windows-Optimize-Harden-Debloat#94]
**Describe the bug*

bitlocker is requiring a recovery key (which I don’t have) and when I goto recovery, open command prompt and run a command that allows me to enter the decryption key (NOT the recovery key), it says invalid when I 100% know it’s correct (I believe the script changed it). 

I’m on windows 10 BTW

**To Reproduce**
I suspended bitlocker, ran the script, restarted pc, then I tried resuming bitlocker and it had conflicting settings, I went into gpedit and fixed it, then I restarted pc 

**Expected behavior**
Bitlocker is suppose to just ask for the decryption key not the recovery, and when going to CMD and entering decryption it says it’s wrong.

**Screenshots**
For some weird reason, github wouldn’t let me upload pictures

https://imgur.com/a/WHXUQHh

**Comment by simeononsecurity** [comment]
> *_Describe the bug_
> 
> bitlocker is requiring a recovery key (which I don’t have) and when I goto recovery, open command prompt and run a command that allows me to enter the decryption key (NOT the recovery key), it says invalid when I 100% know it’s correct (I believe the script changed it).
> 
> I’m on windows 10 BTW
> 
> **To Reproduce** Steps to reproduce the behavior: I suspended bitlocker, ran the script, restarted pc, then I tried resuming bitlocker and it had conflicting settings, I went into gpedit and fixed it, then I restarted pc
> 
> **Expected behavior** Bitlocker is suppose to just ask for the decryption key not the recovery, and when going to CMD and entering decryption it says it’s wrong.
> 
> **Screenshots** For some weird reason, github wouldn’t let me upload pictures
> 
> https://imgur.com/a/WHXUQHh

That is odd, that never happened in our testing. We'll take some time to try and recreate it. But if you're at this point the only thing you can do is overwrite the drive with a fresh copy of windows.

By any chance was this an older bitlocker drive, say originally encrypted on older version of windows or older version of windows 10? Was the system dual booted in any way? And what TPM version does your system have?

**Comment by simeononsecurity** [comment]
> Hi,
> 
> I completely forgot to mention (and forget in general) that **I’m on Tiny10**, and **I do not have TPM** (I changed group policy so it’d work without it, while fixing clashing settings). I also did **lots and lots of other hardening on my computer**, but, I can’t think of a reason for my bitlocker password to be changed.

Non standard installations like that aren't supported. Your password wasn't changed, you likely just implemented an invalid configuration that resulted in the issues you occurred. Since we don't support modified versions of windows, you've done other custom hardening, and there is no way to confirm your settings we can't really help you.
